### ISSUE TITLE
Inclusion in gOSINT 

### ISSUE THREAD

**Issue by Nhoya** [UKHomeOffice/repo-security-scanner#15]
Hi, i was wondering if for you is ok if i includes this project in gOSINT https://github.com/Nhoya/gOSINT

**Comment by techjacker** [comment]
Go ahead

**Comment by Nhoya** [comment]
Well, seems faster and more efficient to just use  the library https://github.com/techjacker/diffence 
I close this PR, thank you for the help anyway
