### ISSUE TITLE
Running on a Mac

### ISSUE THREAD

**Issue by alepeltier** [UKHomeOffice/repo-security-scanner#17]
Hello,

I've been using the scan repo binary on a Linux box but now have a requirement to run it on a Mac as well. 

Will the code run on a Mac or is it Linux only?

**Comment by techjacker** [comment]
Yes it will. If downloading a precompiled binary then make sure you choose the `-darwin-amd64.tar.gz` version from the [releases](https://github.com/UKHomeOffice/repo-security-scanner/) page.

If installing with go then a `go get github.com/UKHomeOffice/repo-security-scanner` will work on any platform.

**Comment by alepeltier** [comment]
fasntastic thank you
