### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by encodedwitch** [UKHomeOffice/repo-security-scanner#25]
Hey there! I was checking the project and was wondering if there's still certain kind of maintenance of it. I'd love to collaborate with whatever roadmap you all created for it

**Comment by chrisns** [comment]
Hi, not really any current maintenance, the industry as a whole has moved a lot with commercial players offering very similar with significant advantages since we created this way back when.
Is there anything you saw here, that you found particularly interesting and worth bringing up to scratch?
Thanks
Chris

**Comment by RobJohnsonHO** [comment]
Hi both, with this in mind, I am moving this to attic. Thanks, Rob

**Comment by techjacker** [comment]
Hi Rob, what does moving to the attic mean?

**Comment by RobJohnsonHO** [comment]
Hi @techjacker,

At the moment, its a buffer zone for repos that can be either deleted or archived.  As there is very little ownership of repos, I'm concerned to do anything more permanent to repos until absolutely sure it is not needed.  There is a UKHomeOffice-attic organisation which I've moving these to in the short term whilst we find out if they are being used.

Any questions, please get in touch, robert.johnson@digital.homeoffice.gov.uk.

**Comment by techjacker** [comment]
Thanks for the info Rob.

It seems a shame to delete or archive it when the community is still getting value from it. I'd be happy to take ownership of it if HO doesn't want the responsibility of maintaining it any longer. I'm confident I could take on the responsibility as I authored most of the code.

**Comment by RobJohnsonHO** [comment]
No problem Andrew.

If any sort of value is being had, then happy to leave it in attic or even the main organisation!
There hadn't been any contributions or any actions on it for many years so it was assumed that it wasn't in use.

Happy to leave in attic for now.  Have you still got access to it now?

**Comment by techjacker** [comment]
Ok thanks Rob.

I just have read access but don't worry if it's a pain to grant write.
