### ISSUE TITLE
Fatal Error on macOS Monterey

### ISSUE THREAD

**Issue by ghost** [UKHomeOffice/repo-security-scanner#26]
The latest release doesn't seem to work on macOS Monterey, I'm getting:

fatal error: runtime: bsdthread_register error

runtime stack
runtime.throw(0x1121631, 0x21)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0x7ff7bfeff900 sp=0x7ff7bfeff8e0
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0xa0 fp=0x7ff7bfeff930 sp=0x7ff7bfeff900
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:486 +0xa1 fp=0x7ff7bfeff970 sp=0x7ff7bfeff930
runtime.rt0_go(0x7ff7bfeff9a0, 0x1, 0x7ff7bfeff9a0, 0x1000000, 0x1, 0x7ff7bfeffb10, 0x0, 0x7ff7bfeffb19, 0x7ff7bfeffb35, 0x7ff7bfeffb44, ...)
	/usr/local/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7ff7bfeff978 sp=0x7ff7bfeff970 

Is anyone supporting this anymore. ?

**Comment by techjacker** [comment]
I've raised a PR to fix this https://github.com/UKHomeOffice-attic/repo-security-scanner/pull/27

**Comment by dhcrees** [comment]
Hi is there any chance of getting this merged and the binaries created please.    Would really appreciate getting this working again on MacOs 12

**Comment by techjacker** [comment]
@dhcrees Big apologies for the delay on this, it caught me at a really busy moment and things have only just finally calmed down!

I've now merged the PR and have added a github actions workflow to automatically upload the artifacts. You can find the latest release [here](https://github.com/techjacker/repo-security-scanner/releases/tag/0.4.1).

**Comment by dhcrees** [comment]
Many thanks for your help with this..
